name: Build & Publish Release APK

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2

    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build Release APK
      run: cd obv_messenger/ && ./gradlew assembleRelease

    - name: Releasing using Hub
      if: startsWith(github.ref, 'refs/tags/v')
      uses: kyze8439690/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       APP_FOLDER: app/build/outputs/apk/prod/release
